config/routes.rb
Tapsell::Application.routes.draw do

  get "offers/listings/:id" => "offers#confirm_listings_page", as: 'new_offer'
  post "offers/listings/:id" => "offers#create_new_offer", as: 'offer'
  get "offers/listings/:id/confirmation" => "offers#offer_confirmation", as: 'offer_confirmation'

  get "users/message/accept/:id" => "messages#accept_offer_message", as: 'accept_offer_message'
  get "users/message/decline/:id" => "messages#decline_offer_message", as: 'decline_offer_message'

  get "users/:id/message" => "messages#index", as: 'messages'
  get "update_msg_chain" => "messages#update_msg_chain", as: 'update_msg_chain'
  post "users/:id/message" => "messages#create", as: 'new_message'
  
  get "listings/search" => "listings#search_listings", as: 'search_listings'
  get "listings/:id/confirm" => "listings#confirm_listing", as: 'confirm_listing'
  post "listings/:id/direct_message" => "listings#direct_message", as: 'direct_message'
  get "newest_listings" => "listings#newest_listings", as: 'newest_listings'
  get "oldest_listings" => "listings#oldest_listings", as: 'oldest_listings'
  get "low_price_listings" => "listings#low_price_listings", as: 'low_price_listings'
  get "high_price_listings" => "listings#high_price_listings", as: 'high_price_listings'
  get "all_listings" => "listings#all_listings", as: 'all_listings'
  get "book_listings" => "listings#book_listings", as: 'book_listings'
  get "apparel_listings" => "listings#apparel_listings", as: 'apparel_listings'
  get "electronic_listings" => "listings#electronic_listings", as: 'electronic_listings'
  get "home_listings" => "listings#home_listings", as: 'home_listings'
  get "ticket_listings" => "listings#ticket_listings", as: 'ticket_listings'
  get "other_listings" => "listings#other_listings", as: 'other_listings'

  get "users/:id/user_settings" => "user_settings#index", as: 'user_settings'
  post "users/:id/user_settings" => "credit_cards#create_card", as: 'create_card'

  get "users/:id/view" => "users#show_public", as: 'public_profile'

  post "users/:id/photo" => "users#new_photo", as: 'new_user_photo'

  get "users/:id/listings" => "listings#show_my_listings", as: 'my_listings'

  get "users/:id/dashboard" => "dashboard#show", as: 'dashboard'

  get "reviews/:id" => "reviews#new", as: 'new_review'
  post "reviews/:id" => "reviews#create", as: 'review'

  match '/sign-up', to: 'users#new', via: 'get'
  match 'sign-in', to: 'sessions#new', via: 'get', as: 'sign_in'
  match '/sign-out', to: 'sessions#destroy', via: 'delete'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets
  resources :listings
  resources :credit_cards

  get "/tutorial" => "tutorial_pages#landing", as: 'tutorial_landing'
  get "/tutorial/sign_up" => "tutorial_pages#sign_up", as: 'tutorial_sign_up'
  post "/tutorial/create" => "tutorial_pages#create", as: 'tutorial_create_user'
  get "/tutorial/1" => "tutorial_pages#step_one", as: 'tutorial_step_one'
  get "/tutorial/2" => "tutorial_pages#step_two", as: 'tutorial_step_two'
  get "/tutorial/3" => "tutorial_pages#step_three", as: 'tutorial_step_three'
  get "/tutorial/4" => "tutorial_pages#step_four", as: 'tutorial_step_four'
  get "/tutorial/5" => "tutorial_pages#step_five", as: 'tutorial_step_five'
  get "/tutorial/6" => "tutorial_pages#step_six", as: 'tutorial_step_six'
  get "/tutorial/finish" => "tutorial_pages#finish", as: 'tutorial_finish'
  get "/tutorial/get_certificate" => "tutorial_pages#get_certificate", as: 'tutorial_get_cert'

  root :to => 'listings#index'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/launch', to: 'marketing_emails#launch', via: 'get'
  match '/team', to: 'static_pages#team', via: 'get'
  match '/jobs', to: 'static_pages#jobs', via: 'get'
  match '/blog', to: 'static_pages#blog', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/faq', to: 'static_pages#faq', via: 'get'
  match '/buyer_faq', to: 'static_pages#buyer_faq', via: 'get'
  match '/terms', to: 'static_pages#terms', via: 'get'
  match '/privacy', to: 'static_pages#privacy', via: 'get'
  match '/buyer_guarantee', to: 'static_pages#buyer_guarantee', via: 'get'

  namespace :api do
    post 'users' => 'users#create'
    get 'users/profile' => 'users#index'
    post 'users/profile/edit' => 'users#update'
    get 'users/:user_id' => 'users#show'
    post 'sessions' => 'sessions#create'
    delete 'sessions' => 'sessions#destroy'
    get 'listings' => 'listings#index'
    post 'listings' => 'listings#create'
    delete 'listings' => 'listings#destroy'
    get 'messages' => 'messages#index'
    post 'messages' => 'messsages#create'
    get 'messages/:msg_chain_id/chain' => 'messages#messages_in_chain',
      :msg_chain_id => /[\w.-]+/
  end

end

app/models/message.rb
class Message < ActiveRecord::Base

  belongs_to :message_chain
  belongs_to :sender, :class_name => "User", :foreign_key => "sender_id"

  # Types of messages, offer having the option to accept or decline
  TYPE_OFFER = "offer"
  TYPE_DEFAULT = "default"
  TYPE_ADMIN = "admin"
  TYPE_LISTING_REMOVED = "listing_removed"
  TYPE_LISTING_SOLD = "listing_sold"

  # Validations
  # -----------

  validates_presence_of :content,
                        :unless => Proc.new {|u| u.content.nil? }
  validates_length_of :content,
                      :within => 1..2000,
                      :too_short => "must be at least 1 character",
                      :too_long => "must be no more than 2000 characters",
                      :unless => Proc.new {|u| u.content.blank? || u.content.nil? }

  validates_presence_of :sender,
                        :unless => Proc.new {|u| u.sender.nil? }

  validates_presence_of :message_chain,
                        :unless => Proc.new {|u| u.message_chain.nil? }

  def api_hash
    {
      message_id: self.id,
      sender: self.sender.api_hash,
      listing_id: self.message_chain.listing_id,
      content: self.content,
      type: self.message_type
    }
  end

end

app/controllers/api/messages_controller.rb
class Api::MessagesController < Api::ApiController
  def index
    # fetch message chains of current user, including
    # top message of msg chain
    msg_chains = @current_user.message_chains
    render json: {
      error: nil,
      data: msg_chains.map { |m| m.api_hash }
    }
  end

  def create
    msg_chain = MessageChain.send_message(@current_user.id, params[:listing_id], 
            params[:content], params[:type])
    render json: {
      error: nil,
      data: msg_chain.api_hash(true)
    }
  end

  def messages_in_chain
    msg_chain = MessageChain.find_by_id(params[:msg_chain_id])
    render json: {
      error: nil,
      data: msg_chain.api_hash(true)
    }
  end

  def update
    # updating statuses (ex: read)

  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :signed_in_user, only: [:index, :create, :show, :destroy]

  def index
    @current_user = current_user
    ordered_message_chains = @current_user.message_chains.sort_by &:updated_at
    @msg_chains = ordered_message_chains.reverse
    @current_msg_chain = @msg_chains[0]
    if @current_msg_chain.present?
      if @current_msg_chain.seller == current_user
        @other_user = @current_msg_chain.buyer
      else
        @other_user = @current_msg_chain.seller
      end
    end

    # clear notification count
    @current_user.notification_count = 0
    @current_user.save
    
    @greeting = Greeting.random_greeting
  end

  def update_msg_chain
    # TODO: so friggen hackish...
    @current_user = current_user
    @current_msg_chain = MessageChain.find(params[:msg_chain])
    ordered_message_chains = @current_user.message_chains.sort_by &:updated_at
    @msg_chains = ordered_message_chains.reverse

    # mark the currently clicked message chain as read/clean
    if @current_msg_chain.seller == current_user
      @current_msg_chain.update_column(:seller_dirty, false)
      @other_user = @current_msg_chain.buyer
    else
      @current_msg_chain.update_column(:buyer_dirty, false)
      @other_user = @current_msg_chain.seller
    end
    @current_msg_chain.save!
  end

  def create
    if params[:msg_chain_id].present? || params[:listing_id].present?
      @msg_chain = MessageChain.send_message(@current_user.id, params[:listing_id],
              params[:content], nil, params[:msg_chain_id], nil)
    end
    redirect_to action: 'index'
  end

  def destroy
  end

  def show
    @msg_chain = MessageChain.find_by_id(params[:msg_chain_id])
  end

  def accept_offer_message
    message_chain = MessageChain.find_by_id(params[:id].to_i)
    offer = message_chain.offer
    begin
      Offer.accept_offer(current_user, offer)
    rescue => e
      raise "Accepting offer error: #{e.message}"
    end
    MessageChain.send_message(current_user.id, message_chain.listing, "#{message_chain.seller.first_name.titleize} #{message_chain.seller.last_name.titleize} has accepted #{message_chain.buyer.first_name.titleize}'s offer.", Message::TYPE_DEFAULT,
      message_chain.id, nil)
    offer.initialize_delivery_timer
    
    # Send notification emails to seller and buyer
    buyer = offer.buyer
    seller = offer.seller
    Notifier.delay.send_offer_accepted_email(buyer, offer)
    Notifier.delay.send_offer_acceptance_confirmation_email(seller, offer)
    redirect_to action: 'index'
  end

  def decline_offer_message
    message_chain = MessageChain.find_by_id(params[:id].to_i)
    offer = message_chain.offer
    offer.cancel
    MessageChain.send_message(current_user.id, message_chain.listing, "#{message_chain.seller.first_name.titleize} #{message_chain.seller.last_name.titleize} has declined #{message_chain.buyer.first_name.titleize}'s offer.", Message::TYPE_DEFAULT,
      message_chain.id, nil)
    # Send offer rejected email to buyer
    buyer = offer.buyer
    Notifier.delay.send_offer_rejected_email(buyer, offer)
    redirect_to action: 'index'
  end
end

app/views/messages/_message_create.html.erb
<%= form_tag messages_path(current_user), :method => :post do %>
  <div class="col-xs-12 message-input-content">
    <div class="col-xs-10 no-pad">
      <textarea class="col-xs-12" name="content" placeholder="Type your message here" required oninvalid="this.setCustomValidity(' ')" onchange="this.setCustomValidity('')"></textarea>
    </div>
    <div class="pull-right">
      <% if current_user.image.present? %>
        <%= image_tag current_user.image.image.thumbnail.url, class: "avatar img-responsive img-circle" %>
      <% else %>
        <%= image_tag "no_image.png", class: "avatar img-responsive img-circle" %>
      <% end %>
    </div>
  </div>
  <div class="col-xs-12 no-pad text-right btn send-btn">
    <% if @current_msg_chain.present? %>
      <%= hidden_field_tag :listing_id, @current_msg_chain.listing_id %>
      <%= hidden_field_tag :msg_chain_id, @current_msg_chain.id %>
    <% end %>
    <%= submit_tag "Submit Message" %>
  </div>
<% end %>

app/views/messages/_message_header.html.erb
<% if @current_msg_chain.present? %>
  <% # handle direct message case %>
  <% status = @current_msg_chain.offer.try(:status) %>
  <% if status == Offer::STATUS_WAITING_FOR_SELLER_RESPONSE %>
    <% if current_user == @current_msg_chain.buyer %>
      <%= render "message_header_buyer_waiting" %>
    <% else %>
      <%= render "message_header_accept_decline" %>
    <% end %>
  <% elsif status == Offer::STATUS_DENIED %>
    <%= render "message_header_decline" %>
  <% elsif status == Offer::STATUS_ACCEPTED %>
    <%= render "message_header_accept" %>
  <% elsif status == Offer::STATUS_TRANSACTION_SUCCESSFUL %>
    <% if current_user == @current_msg_chain.buyer %>
      <%= render "message_header_success_buyer" %>
    <% else %>
      <%= render "message_header_success_seller" %>
    <% end %>
  <% else %>
    <h3>
      Conversation with
      <%= @other_user.first_name %>
      about
      <%= link_to @current_msg_chain.listing.title, listing_path(@current_msg_chain.listing) %>
    </h3>
  <% end %>
<% end %>

app/views/messages/_message_header_accept.html.erb
<div class="col-xs-10 right-heading" id="message-header">
	<h4 class="title">
		<span class="name"><%= @current_msg_chain.seller.first_name.titleize %></span>
		and complete transaction 
		<span class="time-accept"><%= distance_of_time_in_words(Time.now, @current_msg_chain.offer.target_time_for_delivery) %></span>
		left to meet up and complete transaction 
	</h4>
	<h4 class="title">
		<span class="pull-left img-accept">
			<%= image_tag image_url("tapsell-accept.png"), class: "pull-left" %>
			<span class="pull-left">ACCEPTED</span>
		</span>
		<!-- <span class="pull-left listing-name">"<%#= @listing.name.titleize %>" @ </span> -->
		<span class="pull-left listing-name">- <%= @current_msg_chain.listing.title.titleize %> @ </span>
		<!-- <span class="pull-left listing-name">"<%#= @listing.name.titleize %>" @ </span> -->
		<span> &nbsp; <%= number_to_currency(@current_msg_chain.offer.price, :locale => 'en_us', :precision => 0) %>.</span>
	</h4>

	<%#= render "message_header" %>
</div><!-- end of right-heading -->

app/views/messages/_message_header_accept_decline.html.erb
<<<<<<< HEAD
<div class="col-xs-7 right-heading" id="message-header">
	<h4 class="title">
		Clone made an offer of
		<span class="price">$39.00</span>
		for
		<span class="subject">FIFTY SHADES OF GREY</span> 
	</h4>
	<p class="col-xs-12 no-pad second-title">
		<span class="pull-left">YOU HAVE</span>
		<span class="pull-left time">13hr 43min</span>
		<span class="pull-left">LEFT TO:</span>
		<span class="pull-left btn-content">
			<%= link_to "javascript:void(0);", class: "btn btn-accept text-center" do %>
				<i class="pull-left"></i>
				ACCEPT
			<% end %>
			<%= link_to "javascript:void(0);", class: "btn btn-decline text-center" do %>
=======
<div class="col-xs-10 right-heading" id="message-header">
	<h4 class="title">
		<%= "#{@other_user.first_name.titleize} made an offer of" %>
		<span class="price"><%= number_to_currency(@current_msg_chain.offer.price, :locale => 'en_us', :precision => 0) %></span>
		for
		<span class="subject"><%= link_to @current_msg_chain.offer.listing.title, listing_path(@current_msg_chain.listing) %></span> 
	</h4>
	<p class="col-xs-12 no-pad second-title">
		<span class="pull-left">YOU HAVE</span>
		<% if @current_msg_chain.offer.target_time_for_accepting.present? %>
			<span class="pull-left time"><%= distance_of_time_in_words(Time.now, @current_msg_chain.offer.target_time_for_accepting) %></span>
		<% else %>
			<span class="pull-left time">LESS THAN 1 DAY </span>
		<% end %>
		<span class="pull-left">LEFT TO:</span>
		<span class="pull-left btn-content">
			<%= link_to accept_offer_message_path(@current_msg_chain.id), class: "btn btn-accept text-center" do %>
				<i class="pull-left"></i>
				ACCEPT
			<% end %>
			<%= link_to decline_offer_message_path(@current_msg_chain.id), class: "btn btn-decline text-center" do %>
>>>>>>> c9efa0f5dfb4d48c381d8b7f986e19497143f67b
				<i class="pull-left"></i>
				DECLINE
			<% end %>
		</span>
	</p>

	<%#= render "message_header" %>
</div><!-- end of right-heading -->

app/views/messages/_message_header_buyer_waiting.html.erb
<div class="col-xs-10 right-heading" id="message-header">
  <h4 class="title">
    <%= "You made an offer of" %>
    <span class="price"><%= number_to_currency(@current_msg_chain.offer.price, :locale => 'en_us', :precision => 0) %></span>
    for
    <span class="subject"><%= link_to @current_msg_chain.offer.listing.title, listing_path(@current_msg_chain.listing) %></span> 
  </h4>
  <h4 class="title">
    Waiting for response from 
    <span class="subject"><%= link_to @current_msg_chain.seller.first_name.titleize, public_profile_path(@current_msg_chain.seller.id) %></span> 
  </h4>
  <%#= render "message_header" %>
</div><!-- end of right-heading -->

app/views/messages/_message_header_decline.html.erb
<<<<<<< HEAD
<div class="col-xs-7 right-heading" id="message-header">
	<h4 class="title">
		<span class="name">Vincent</span>
		made an offer of
		<span class="price">$39.00</span>
		for
		<span class="subject">"IKEA Sofa Taupe Leather"</span>
=======
<div class="col-xs-10 right-heading" id="message-header">
	<h4 class="title">
		<span class="name"><%= @current_msg_chain.buyer.first_name.titleize %></span>
		made an offer of
		<span class="price"><%= number_to_currency(@current_msg_chain.offer.price, :locale => 'en_us', :precision => 0) %></span>
		for
		<span class="subject"><%= link_to @current_msg_chain.offer.listing.title, listing_path(@current_msg_chain.listing) %></span>
>>>>>>> c9efa0f5dfb4d48c381d8b7f986e19497143f67b
	</h4>
	<h4 class="title">
		<span class="pull-left img-decline">
			<%= image_tag image_url("tapsell-decline.png"), class: "pull-left" %>
			<span class="pull-left">DECLINED</span>
		</span>
	</h4>

	<%#= render "message_header" %>
</div><!-- end of right-heading -->

app/views/messages/_message_header_success_buyer.html.erb
<div class="col-xs-7 right-heading" id="message-header">
	<h4 class="title">
		Yay +1 win! Enjoy your
<<<<<<< HEAD
		<span class="subject orange">IKEA Sofa Taupe Leather</span>
	</h4>
	<h4 class="title">
		Your scored this at your offer of
		<span>$50.00.</span>
=======
		<span class="subject orange"><%= link_to @current_msg_chain.offer.listing.title, listing_path(@current_msg_chain.listing) %></span>
	</h4>
	<h4 class="title">
		Your scored this at your offer of
		<span><%= number_to_currency(@current_msg_chain.offer.price, :locale => 'en_us', :precision => 0) %>.</span>
>>>>>>> c9efa0f5dfb4d48c381d8b7f986e19497143f67b
	</h4>

	<%#= render "message_header" %>
</div><!-- end of right-heading -->

app/views/messages/_message_header_success_seller.html.erb
<div class="col-xs-7 right-heading" id="message-header">
	<h4 class="title">
		Congratulations! You earned 
<<<<<<< HEAD
		<span class="price">$39.00</span>
		for your team
		<span class="subject">FIFTY SHADES OF GREY</span> 
=======
		<span class="price"><%= number_to_currency(@current_msg_chain.offer.price, :locale => 'en_us', :precision => 0) %></span>
		for your team
		<span class="subject"><%= link_to @current_msg_chain.offer.listing.title, listing_path(@current_msg_chain.listing) %></span> 
>>>>>>> c9efa0f5dfb4d48c381d8b7f986e19497143f67b
	</h4>
	<%#= render "message_header" %>
</div><!-- end of right-heading -->

app/views/messages/_messages.html.erb
<% if @current_msg_chain.present? %>
  <%- for @message in @current_msg_chain.messages.sort_by(&:created_at) %>
    <div class="col-xs-12" style="overflow">
      <% if @current_user == @message.sender %>
        <div class="message-item col-xs-12 col-md-9 buyer pull-right">
            <span>
              <%= image_tag "tapsell_arrow_right.png" %>
            </span>
          <p>
            <%= @message.content %>
          </p>
        </div>
      <% else %>
        <div class="message-item col-xs-12 col-md-9 seller">
          <span>
            <%= image_tag "tapsell_arrow_left.png" %>
          </span>
          <p>
            <%= @message.content %>
          </p>
        </div>
      <% end %>
      <div class="col-xs-12 col-md-9 pull-left no-pad">
        <p class="text-right time"><%= distance_of_time_in_words(Time.now, @message.created_at, false, { vague: true }) %></p>
      </div>
    </div>
  <% end %>
<% end %>

app/views/messages/_msg_chains.html.erb
<%- for @msg_chain in @msg_chains %>
  <%= link_to update_msg_chain_path(:msg_chain => @msg_chain), :remote => true, :class => "message-user-list col-xs-12" do %>
    <% if @msg_chain.seller == current_user %>
      <% other_user = @msg_chain.buyer %>
      <% @dirty_flag = @msg_chain.seller_dirty %>
    <% else %>
      <% other_user = @msg_chain.seller %>
      <% @dirty_flag = @msg_chain.buyer_dirty %>
    <% end %>
    <div class="col-xs-12 message-user-content">
      <div class="col-xs-4 no-pad">
        <% if @dirty_flag == true %>
          <%= image_tag "tapsell_big_circle_dot.png", class: "pull-left dot" %>
        <% end %>
        <% if other_user.image.present? %>
          <%= image_tag other_user.image.image.thumbnail.url, class: "pull-left img-circle img-responsive avatar" %>
        <% else %>
          <%= image_tag "no_image.png", class: "pull-left img-circle img-responsive avatar" %>
        <% end %>
      </div>
      <div class="col-xs-8 no-pad">
        <div class="col-xs-12 no-pad message-info">
          <div class="pull-left">
            <%= other_user.first_name.titleize + " " + other_user.last_name.titleize %>
          </div>
          <div class="pull-right">
            <%= distance_of_time_in_words(Time.now, @msg_chain.updated_at, false, { vague: true }) %>
          </div>
        </div>
        <div class="col-xs-12 no-pad message-preview">
          <p>
            <%= @msg_chain.most_recent_message.content[0...100] %>
          </p>
        </div>
      </div>
    </div> <!-- end of message-user-content -->
  <% end %> <!-- end of link -->
<% end %>

app/views/messages/index.html.erb
<%= content_for :javascript_contents do %>
	<%= javascript_include_tag "messages" %>
<% end %>
<%= content_for :stylesheet_contents do %>
	<%= stylesheet_link_tag "messages", "listings" %>
<% end %>
<div class="col-xs-12 message-container no-pad">
	<div class="message-header col-xs-12 text-center">
<<<<<<< HEAD
		<div class="center-block">
			<h1 class="no-marg text-center">
				<%= image_tag image_url("tapsell_sun.png"), class: "", style: "margin-top: -9px;" %>
				75<sup>o</sup>F and Sunny in San Francisco
			<%#= @greeting %>
			</h1>
		</div>
=======
		<h1>
			<%= @greeting %>
		</h1>
>>>>>>> c9efa0f5dfb4d48c381d8b7f986e19497143f67b
	</div><!-- end of message-header -->

	<%= render "layouts/navigation" %>
	<div class="message-body col-xs-12" style="padding-top: 0;">
		<div class="container">
			<div class="message-box col-xs-12 no-pad">
				<div class="message-heading col-xs-12">
					<div class="col-xs-5 left-heading">
						<ul class="list-inline col-xs-12">
							<li class="list-inline-item"><b>View</b></li>
							<li class="list-inline-item">
								<%= link_to "All", "javascript:void(0);" %>
							</li>
							<li class="list-inline-item">
								<%= link_to "Unread", "javascript:void(0);" %>
							</li>
							<li class="list-inline-item">
								<%= link_to "Pending", "javascript:void(0);", class: "no-dash" %>
							</li>
						</ul>
<<<<<<< HEAD
						<form role="form" class="col-xs-12" style="width: 99%; padding-left: 0;">
							<div class="form-group" style="margin-bottom: 0;">
								<div class="input-group search-input-group">
								  <span class="input-group-addon">
								  	<%= image_tag image_url("tapsell-search.png") %>
								  </span>
								  <input type="text" class="form-control input-lg" placeholder="Search Message">
=======
						<form role="form" class="col-xs-12">
							<div class="form-group">
								<div class="input-group">

>>>>>>> c9efa0f5dfb4d48c381d8b7f986e19497143f67b
								</div>
							</div>
						</form>
					</div><!-- end of left-heading -->

					<%#= render "message_header_accept_decline" %>
					<%#= render "message_header_accept" %>
					<%#= render "message_header_decline" %>
					<%#= render "message_header_success_buyer" %>
					<%= render "message_header_success_seller" %>
					
				</div><!-- end of message-heading -->

				<div class="message-content col-xs-12 no-pad">
					<div class="message-content-left col-xs-5 no-pad" id="message-chains-container">
						<%= render "msg_chains" %>
					</div><!-- end of content-left -->
					<div class="message-content-right col-xs-7">
						<div class="col-xs-12 message-item-container" id="message-item-container">
							<%= render "messages" %>
						</div>
						<div class="message-input-container col-xs-12" id="message-create-container">
							<%= render "message_create" %>
						</div>
					</div>
				</div><!-- end of message-content -->

			</div>
		</div>
	</div><!-- end of message-body -->
</div>

app/views/messages/update_msg_chain.js.erb
$("#message-item-container").html("<%=j render partial: 'messages' %>");
$("#message-chains-container").html("<%=j render partial: 'msg_chains' %>");
$("#message-header").html("<%=j render partial: 'message_header' %>");
$("#message-create-container").html("<%=j render partial: 'message_create' %>");