config/routes.rb
Tapsell::Application.routes.draw do

  get "offers/listings/:id" => "offers#confirm_listings_page", as: 'new_offer'
  post "offers/listings/:id" => "offers#create_new_offer", as: 'offer'
  get "offers/listings/:id/confirmation" => "offers#offer_confirmation", as: 'offer_confirmation'

  get "users/message/accept/:id" => "messages#accept_offer_message", as: 'accept_offer_message'
  get "users/message/decline/:id" => "messages#decline_offer_message", as: 'decline_offer_message'

  get "users/:id/message" => "messages#index", as: 'messages'
  get "update_msg_chain" => "messages#update_msg_chain", as: 'update_msg_chain'
  post "users/:id/message" => "messages#create", as: 'new_message'
  
  get "listings/search" => "listings#search_listings", as: 'search_listings'
  get "listings/:id/confirm" => "listings#confirm_listing", as: 'confirm_listing'
  post "listings/:id/direct_message" => "listings#direct_message", as: 'direct_message'
  get "newest_listings" => "listings#newest_listings", as: 'newest_listings'
  get "oldest_listings" => "listings#oldest_listings", as: 'oldest_listings'
  get "low_price_listings" => "listings#low_price_listings", as: 'low_price_listings'
  get "high_price_listings" => "listings#high_price_listings", as: 'high_price_listings'
  get "all_listings" => "listings#all_listings", as: 'all_listings'
  get "book_listings" => "listings#book_listings", as: 'book_listings'
  get "apparel_listings" => "listings#apparel_listings", as: 'apparel_listings'
  get "electronic_listings" => "listings#electronic_listings", as: 'electronic_listings'
  get "home_listings" => "listings#home_listings", as: 'home_listings'
  get "ticket_listings" => "listings#ticket_listings", as: 'ticket_listings'
  get "other_listings" => "listings#other_listings", as: 'other_listings'

  get "users/:id/user_settings" => "user_settings#index", as: 'user_settings'
  post "users/:id/user_settings" => "credit_cards#create_card", as: 'create_card'

  get "users/:id/view" => "users#show_public", as: 'public_profile'

  post "users/:id/photo" => "users#new_photo", as: 'new_user_photo'

  get "users/:id/listings" => "listings#show_my_listings", as: 'my_listings'

  get "users/:id/dashboard" => "dashboard#show", as: 'dashboard'

  get "reviews/:id" => "reviews#new", as: 'new_review'
  post "reviews/:id" => "reviews#create", as: 'review'

  match '/sign-up', to: 'users#new', via: 'get'
  match 'sign-in', to: 'sessions#new', via: 'get', as: 'sign_in'
  match '/sign-out', to: 'sessions#destroy', via: 'delete'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets
  resources :listings
  resources :credit_cards

  get "/tutorial" => "tutorial_pages#landing", as: 'tutorial_landing'
  get "/tutorial/sign_up" => "tutorial_pages#sign_up", as: 'tutorial_sign_up'
  post "/tutorial/create" => "tutorial_pages#create", as: 'tutorial_create_user'
  get "/tutorial/1" => "tutorial_pages#step_one", as: 'tutorial_step_one'
  get "/tutorial/2" => "tutorial_pages#step_two", as: 'tutorial_step_two'
  get "/tutorial/3" => "tutorial_pages#step_three", as: 'tutorial_step_three'
  get "/tutorial/4" => "tutorial_pages#step_four", as: 'tutorial_step_four'
  get "/tutorial/5" => "tutorial_pages#step_five", as: 'tutorial_step_five'
  get "/tutorial/6" => "tutorial_pages#step_six", as: 'tutorial_step_six'
  get "/tutorial/finish" => "tutorial_pages#finish", as: 'tutorial_finish'
  get "/tutorial/get_certificate" => "tutorial_pages#get_certificate", as: 'tutorial_get_cert'

  root :to => 'listings#index'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/launch', to: 'marketing_emails#launch', via: 'get'
  match '/team', to: 'static_pages#team', via: 'get'
  match '/jobs', to: 'static_pages#jobs', via: 'get'
  match '/blog', to: 'static_pages#blog', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/faq', to: 'static_pages#faq', via: 'get'
  match '/buyer_faq', to: 'static_pages#buyer_faq', via: 'get'
  match '/terms', to: 'static_pages#terms', via: 'get'
  match '/privacy', to: 'static_pages#privacy', via: 'get'
  match '/buyer_guarantee', to: 'static_pages#buyer_guarantee', via: 'get'

  namespace :api do
    post 'users' => 'users#create'
    get 'users/profile' => 'users#index'
    post 'users/profile/edit' => 'users#update'
    get 'users/:user_id' => 'users#show'
    post 'sessions' => 'sessions#create'
    delete 'sessions' => 'sessions#destroy'
    get 'listings' => 'listings#index'
    post 'listings' => 'listings#create'
    delete 'listings' => 'listings#destroy'
    get 'messages' => 'messages#index'
    post 'messages' => 'messsages#create'
    get 'messages/:msg_chain_id/chain' => 'messages#messages_in_chain',
      :msg_chain_id => /[\w.-]+/
  end

end

app/models/listing.rb
class Listing < ActiveRecord::Base

  STATUS_ACTIVE = "active"
  STATUS_REMOVED = "removed"
  STATUS_PURCHASED = "purchased"
	# Relationships - Ordered Alphabetically
	# --------------------------------------

	has_one :address
	has_many :images
	has_many :offers
	has_many :message_chains
	belongs_to :seller, :class_name => "User", :foreign_key => "seller_id"
	belongs_to :buyer, :class_name => "User", :foreign_key => "buyer_id"

	accepts_nested_attributes_for :images

	
  def self.search(search)
	  results = find(:all, :order => 'created_at DESC', :conditions => ['(title ILIKE ? or info ILIKE ?) and status != ?', "%#{search}%", "%#{search}%", STATUS_REMOVED])
	  return results
	end

	def remove
	  # Change status of listing to removed, send deleted message
	  # to each message chain attached to the listing
    self.status = Listing::STATUS_REMOVED
    self.save

    self.message_chains.each do |m|
    	m.offer.cancel
      MessageChain.send_message(self.seller.id, self.id, "#{self.seller.first_name.titleize} has removed this listing.", Message::TYPE_LISTING_REMOVED, m.id, nil)
    end
	end

	def sold_to(offer)
	  # Change status of listing to sold, send deleted message
	  # to each message chain attached to the listing
    self.status = Listing::STATUS_PURCHASED
    self.save

    self.message_chains.each do |m|
      if m.offer != offer
        m.offer.cancel
        MessageChain.send_message(self.seller.id, self.id, "#{self.seller.first_name.titleize} has sold this listing.", Message::TYPE_LISTING_SOLD, m.id, nil)
      end
    end
	end


	# Validations
	# -----------

	validates :seller_id,
				:presence => true
	validates :title,
				:presence => { message: "is missing" }
	validates :price,
				:presence => { message: "is missing" }
	validates :info,
				:presence => { message: "is missing" }

	def api_hash
		images = []
		self.images.each do |i|
			images.push({ :url => i.image.url})
		end
		{
			listing_id: self.id,
			seller: self.seller.api_hash,
			# address: self.address.nil? ? nil : self.address.api_hash,
			title: self.title,
			category: self.category,
			date: self.created_at,
			info: self.info,
			price: self.price,
			status: self.status,
			images: images,
			locality: self.address.nil? ? nil : self.address.locality,
			region: self.address.nil? ? nil : self.address.region
		}
	end

end

app/controllers/api/listings_controller.rb
class Api::ListingsController < Api::ApiController

	before_filter :build_listing, only: [:create]
	before_filter :create_listing, only: [:create]

	def index
		render json: {
			error: nil,
			data: @current_user.listings_as_seller.map{ |l| l.api_hash }
		}
	end

	def create
		render status: 200, json: {
      error: nil,
      data: @listing.api_hash
    }
	end

	private

	def build_listing
		pic_data = []
		if !params[:pic_data_1].blank?
			pic_data.push(params[:pic_data_1])
		end
		if !params[:pic_data_2].blank?
			pic_data.push(params[:pic_data_2])
		end
		if !params[:pic_data_3].blank?
			pic_data.push(params[:pic_data_3])
		end
		if !params[:pic_data_4].blank?
			pic_data.push(params[:pic_data_4])
		end
		images = []
		pic_data.each do |p|
			temp_file = Tempfile.new('tempfile')
			begin
				temp_file.binmode
				temp_file.write(Base64.decode64(p))
				img = Image.new()
				img.image = temp_file
				images.push(img)
			ensure
				temp_file.close
				temp_file.unlink
			end
		end

		@listing = Listing.new(
			seller_id: @current_user.id,
			title: params[:title],
			category: params[:category],
			info: params[:info],
			post_to_craigslist: params[:post_craigslist],
			post_to_fb_timeline: params[:post_facebook],
			post_to_free_for_sale: params[:post_ffs],
			price: params[:price],
			status: params[:status],
			images: images
			)
		if params[:address_id].blank?
			build_and_create_address
			@listing.address = @address
		else
			@listing.address = Address.find(params[:address_id])
		end
	end

	def create_listing
		 begin
      unless @listing.save
        render status: 422, json: {
          error: "Could not create listing"
        }
      end
    rescue ActiveRecord::ActiveRecordError
      render status: 422, json: {
        error: "Could not create listing"
      }
    end
	end

	# TODO(ryan): move this into model?
	def build_and_create_address
		begin
			@address = Address.new(
				street_address: params[:address][:street_address],
				extended_address: params[:address][:extended_address],
				locality: params[:address][:locality],
				region: params[:address][:region],
				postal_code: params[:address][:postal_code],
				phone: params[:address][:phone],
				email: params[:address][:email]
				)

			unless @address.save
				render status: 422, json: {
          error: "Could not create address"
        }
      end
    rescue ActiveRecord::ActiveRecordError
      render status: 422, json: {
        error: "Could not create address"
      }
    end
  end
end 

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :signed_in_user, only: [:new, :create, :destroy]

  def index
    @user = current_user

    # TODO: HACK, can't figure out how to redirect,
    # look at search_listings
    if session[:is_search].present?
      @listings = session[:search_listing_ids].empty? ? Listing.none : Listing.where(id: session[:search_listing_ids]).order("created_at DESC")
    else
      order_listings("created_at DESC")
    end

    # clear session
    session.delete(:is_search)
    session.delete(:search_listing_ids)
  end

  def search_listings
    session[:is_search] = true
    session[:search_listing_ids] = Listing.search(params[:search]).collect(&:id)
    redirect_to :action => :index
  end

  def all_listings
    order_listings("created_at DESC")
  end

  def book_listings
    order_by_category("Books")
  end

  def apparel_listings
    order_by_category("Apparel")
  end

  def electronic_listings
    order_by_category("Electronics")
  end

  def home_listings
    order_by_category("Home")
  end

  def ticket_listings
    order_by_category("Tickets")
  end

  def other_listings
    order_by_category("Other")
  end

  def newest_listings
    order_listings("created_at DESC")
  end

  def oldest_listings
    order_listings("created_at ASC")
  end

  def low_price_listings
    order_listings("price ASC")
  end

  def high_price_listings
    order_listings("price DESC")
  end

  def show_my_listings
    @current_user = current_user
    @listings = @current_user.active_listings_as_seller.sort_by(&:created_at)
    # TODO: HACK
    @listings.reverse!
    @greeting = Greeting.random_greeting
  end

  def new
    @user = current_user
    @listing = Listing.new
    4.times { @listing.images.build }
  end

  def create
    @user = current_user
    @listing = current_user.listings_as_seller.build(listing_params)
    @listing.status = Listing::STATUS_ACTIVE

    # TODO: another sad hack :-(. Images parsing
    images_hash = params["listing"]["images_attributes"]
    if images_hash.present?
      images_hash.values.each do |image|
        img = Image.new(image)
        @listing.images.push(img)
      end
    end
    if @listing.save
      flash[:success] = "Listing created!"
      redirect_to confirm_listing_path(@listing)
      Notifier.delay.send_item_posted_email(@user)
    else
      flash[:notice] = "Oops!  There was a problem creating the listing, please try again.  #{@listing.errors.full_messages.join(', ')}"
      redirect_to new_listing_path
    end
  end

  def show
    @user = current_user
    @listing = Listing.find(params[:id])
  end

  def edit
    @user = current_user
    @listing = Listing.find(params[:id])
  end

  def update
    @listing = Listing.find(params[:id])
    if @listing.update_attributes(listing_params)
      flash[:success] = "Listing update successful!"
      redirect_to @listing
    else
      flash[:notice] = "There was a problem updating your listing.  Please double-check and try again!"
      render 'edit'
    end
  end

  def confirm_listing
    @user = current_user
    @listing = Listing.find(params[:id])
  end

  def destroy
    @listing = Listing.find(params[:id])
    @listing.remove

    redirect_to :action => :show_my_listings
  end

  def direct_message
    @msg_chain = MessageChain.send_message(current_user.id, params[:listing_id],
              params[:content], nil, nil, nil)
    redirect_to :action => :show
  end

private

  def order_listings(sort_detail)
    @listings = Listing.where.not(status: Listing::STATUS_REMOVED).order(sort_detail).page(params[:page]).limit(28)
  end

  def order_by_category(name)
    @listings = Listing.where(category: name).where.not(status: Listing::STATUS_REMOVED).order("created_at DESC").page(params[:page]).limit(28)
  end

  def listing_params
    params.require(:listing).permit(:title, :category, :info, :post_to_craigslist, :post_to_fb_timeline, :post_to_fb_timeline, :price)
  end

end

app/helpers/listings_helper.rb
module ListingsHelper

	def categories
		["Books", "Apparel", "Electronics", "Home", "Tickets", "Other"]
	end

	def all
		@listings.paginate(:page => params[:page], :per_page => 28)
	end

	def books
		paginate_category("Books", 28)
	end

	def fashions
		paginate_category("Apparel", 28)
	end

	def electronics
		paginate_category("Electronics", 28)
	end

	def beauties
		paginate_category("Home", 28)
	end

	def home
		paginate_category("Tickets", 28)
	end

	def hobbies
		paginate_category("Other", 28)
	end

	def paginate_category(name, number)
		@listings.where(category: name).paginate(:page => params[:page], :per_page => number)
	end
end

app/views/listings/_listing_details.html.slim
.col-xs-12
  .alert.alert-success.marg-top-30.hide
.col-xs-12
  .row
    .col-xs-10.pad-right-0
      #carousel-example-generic.carousel.slide data-ride=("carousel")
        .carousel-inner
          - if @listing.images.present?
            - if @listing.status.eql?(Listing::STATUS_PURCHASED)
              - @listing.images.each_with_index do |listing, index|
                - if index.eql?(0)
                  .item.active
                    .watermark.text-center
                      .watermark-content
                        h3 SOLD
                    = image_tag image_url(listing.image), class: "listing-image"
                - else
                  .item
                    .watermark.text-center
                      .watermark-content
                        h3 SOLD
                    = image_tag image_url(listing.image), class: "listing-image"
            - else
              - @listing.images.each_with_index do |listing, index|
                - if index.eql?(0)
                  .item.active
                    = image_tag image_url(listing.image), class: "listing-image"
                - else
                  .item
                    = image_tag image_url(listing.image), class: "listing-image"
          - else
            - if @listing.status.eql?(Listing::STATUS_PURCHASED)
              .item.active
                .watermark.text-center
                  .watermark-content
                    h3 SOLD
                = image_tag image_url('no_pic.jpg'), class: "listing-image"
            - else
              .item.active
                = image_tag image_url('no_pic.jpg'), class: "listing-image"
    .col-xs-2.text-right.pad-left-0
      ol.carousel-indicators
        - @listing.images.each_with_index do |listing, index|
          - if index.eql?(0)
            li data-target="#carousel-example-generic" data-slide-to="#{index}" class=" thumb-slider active" style=("background-image: url(#{image_url(listing.image)});")
          - else
            li.thumb-slider data-target="#carousel-example-generic" data-slide-to="#{index}" style=("background-image: url(#{image_url(listing.image)});")
.col-xs-12.product-description
  = @listing.info

javascript:
  $(document).ready(function(){
    var watHeight = $(".item").height(); 
    $(".watermark-content").height(watHeight);

    $(".carousel").carousel();

    var imageWidth = $(".listing-image").width();
    var imageHeight = $(".listing-image").height();
    if(imageHeight >= imageWidth) {
      $(".listing-image").addClass("vertical-image");
    }
    else if(imageWidth >= imageHeight) {
      $(".listing-image").css("width", "400px");
    }
  });

- if session[:sosmed_type]
  = render "home/modal_verify"
  javascript:
    $(document).ready(function(){
      $("#verify-modal").modal({
        backdrop: "static",
        keyboard: false
      })
    });

app/views/listings/_listing_items.html.slim
- @listings.each do |listing|
  .col-xs-6.col-md-3.listing-item data-price="#{listing.price.to_i}"
    .col-xs-12.col-md-12.thumbnail
      h5.col-xs-12.no-pad= truncate(listing.title.html_safe, length: 25)
      - if listing.images.present?
        = link_to listing_path(listing),class: "col-xs-12 no-pad"
          - if listing.status == Listing::STATUS_PURCHASED
            .watermark.text-center
              .watermark-content
                h3 SOLD
            .image-container style="background-image: url('#{image_url(listing.images[0].image.url)}')"
          - else
            .image-container style="background-image: url('#{image_url(listing.images[0].image.url)}')"
      - else
        = link_to listing_path(listing),class: "col-xs-12 no-pad"
          - if listing.status == Listing::STATUS_PURCHASED
            .watermark.text-center
              .watermark-content
                h3 SOLD
            .image-container style="background-image: url('#{image_url('no_pic.jpg')}')"
          - else
            .image-container style="background-image: url('#{image_url('no_pic.jpg')}')"
      .col-xs-6.no-pad
        .time-post.pull-left= distance_of_time_in_words(Time.now, listing.created_at, false, { vague: true })
        ago
      .col-xs-6.no-pad
        .price.pull-right class="price-#{listing.price.to_i}" id="#{listing.price.to_i}"
          | $
          = listing.price.to_i

javascript:
  $(document).ready(function(){
    var watHeight = $(".item").height(); 
    $(".watermark-content").height(watHeight);

    $(".carousel").carousel();

    var imageWidth = $(".listing-image").width();
    var imageHeight = $(".listing-image").height();
    if(imageHeight >= imageWidth) {
      $(".listing-image").addClass("vertical-image");
    }
    else if(imageWidth >= imageHeight) {
      $(".listing-image").css("width", "400px");
    }
  });

- if session[:sosmed_type]
  = render "home/modal_verify"
  javascript:
    $(document).ready(function(){
      $("#verify-modal").modal({
        backdrop: "static",
        keyboard: false
      })
    });

app/views/listings/_listing_navigation.html.erb
<div class="col-xs-12">
	<div class="container navigation-child-container">
		<ul class="nav nav-pills">
			<li class="<%= controller_name.eql?('dashboard') ? "active" : "" %>">
				<%= link_to "DASHBOARD", dashboard_path(current_user.id), class: "nav-link" %>
			</li>
			<li class="<%= controller_name.eql?('messages') ? "active" : "" %>">
				<%= link_to "INBOX", messages_path(current_user.id), class: "nav-link" %>
			</li>
			<li class="<%= controller_name.eql?('listings') ? "active" : "" %>">
				<%= link_to "MY LISTINGS", my_listings_path(current_user.id), class: "nav-link" %>
			</li>
			<li class="<%= controller_name.eql?('users') ? "active" : "" %>">
				<%= link_to "PROFILE", user_path(current_user.id), class: "nav-link" %>
			</li>
			<li class="<%= controller_name.eql?('payment_settings') ? "active" : "" %>">
				<%= link_to "SETTINGS", user_settings_path(current_user.id), class: "nav-link" %>
			</li>
		</ul>
	</div>
</div>

app/views/listings/all_listings.js.erb
$("#loader-container").addClass("hide");
$("#container-listing").html("<%=j render partial: 'listing_items' %>");

app/views/listings/book_listings.js.erb
$("#loader-container").addClass("hide");
$("#container-listing").html("<%=j render partial: 'listing_items' %>");

app/views/listings/electronic_listings.js.erb
$("#loader-container").addClass("hide");
$("#container-listing").html("<%=j render partial: 'listing_items' %>");

app/views/listings/index.html.slim
= content_for :stylesheet_contents do
  = stylesheet_link_tag "products"

.col-xs-12.header-title-container
  .container.text-center
    h1 Get your browse on!

    = form_tag search_listings_path, :method => "get", role: "form", html: {class: "col-xs-12"}
      .input-group
        = text_field_tag :search, params[:search], class: "form-control", placeholder: "Looking for something?"
        .input-group-btn
          button.btn.btn-default.listing-search-button type="submit" name=""
            i.glyphicon.glyphicon-search


.col-xs-12.navigation-container
  .container
    h4 BROWSE
    ul.nav.nav-pills
      li.all-items.active
        = link_to "All", all_listings_path, class: "all-link filter-category", remote: true
      li.book-items
        = link_to "Books", book_listings_path, class: "book-link filter-category", remote: true
      li.apparel-items
        = link_to "Apparel", apparel_listings_path, class: "apparel-link filter-category", remote: true
      li.electronic-items
        = link_to "Electronics", electronic_listings_path, class: "electronic-link filter-category", remote: true
      li.home-items
        = link_to "Home", home_listings_path, class: "home-link filter-category", remote: true
      li.ticket-items
        = link_to "Tickets", ticket_listings_path, class: "ticket-link filter-category", remote: true
      li.other-items
        = link_to "Other", other_listings_path, class: "other-link filter-category", remote: true
      .dropdown.pull-right
        = link_to "javascript:void(0);", data: {toggle: "dropdown"}
          | SORT BY
          span.glyphicon.glyphicon-play
        ul.dropdown-menu role="menu" aria-labelledby="dlabel"
          li.newest.active
            = link_to "Newest Listing", newest_listings_path, class: "newest-link filter-category", remote: true
          li.oldest
            = link_to "Oldest Listing", oldest_listings_path, class: "oldest-link filter-category", remote: true
          li.low-price
            = link_to "Low Price", "javascript:void(0);", class: "low-price-link filter-category"
          li.high-price
            = link_to "High Price", "javascript:void(0);", class: "high-price-link filter-category"
#loader-container.text-center.col-xs-12.animated.fadeInDown.hide
  i.fa.fa-refresh.fa-spin.fa-5x
.col-xs-12
  .container.no-pad
    #container-listing.listing-container.col-xs-12
      = render "listing_items"
#all-paginate.col-xs-12.text-center.animated.fadeInUp
  ul.pagination= will_paginate all
#book-paginate.col-xs-12.text-center.animated.fadeInUp.hide
  ul.pagination= will_paginate books
#fashion-paginate.col-xs-12.text-center.animated.fadeInUp.hide
  ul.pagination= will_paginate fashions
#electronic-paginate.col-xs-12.text-center.animated.fadeInUp.hide
  ul.pagination= will_paginate electronics
#beauty-paginate.col-xs-12.text-center.animated.fadeInUp.hide
  ul.pagination= will_paginate beauties
#home-paginate.col-xs-12.text-center.animated.fadeInUp.hide
  ul.pagination= will_paginate home
#hobbies-paginate.col-xs-12.text-center.animated.fadeInUp.hide
  ul.pagination= will_paginate hobbies

= javascript_include_tag "listings", "jquery.tinysort.min"

app/views/listings/newest_listings.js.erb
$("#loader-container").addClass("hide");
$("#container-listing").html("<%=j render partial: 'listing_items' %>");

app/views/listings/oldest_listings.js.erb
$("#loader-container").addClass("hide");
$("#container-listing").html("<%=j render partial: 'listing_items' %>");

app/views/listings/other_listings.js.erb
$("#loader-container").addClass("hide");
$("#container-listing").html("<%=j render partial: 'listing_items' %>");

app/views/listings/search_listings.js.erb
$("#loader-container").addClass("hide");
$("#container-listing").html("<%=j render partial: 'listing_items' %>");

app/views/listings/show_my_listings.html.erb
<div class="col-xs-12 top-banner">
<<<<<<< HEAD
	<div class="container">
		<div class="center-block content">
			<span class="feature">
				<%= @greeting %>
			</span>
		</div>
	</div>
=======
	<h1>
		<%= @greeting %>
	</h1>
>>>>>>> c9efa0f5dfb4d48c381d8b7f986e19497143f67b
</div>

<%= render "listings/listing_navigation" %>

<div class="col-xs-12 mylisting-container">
	<div class="container">
		<div class="content box-container col-xs-12">
			<div class="heading col-xs-12">
				<span class="title pull-left">
					Your Active Listings
				</span>
				<%= link_to "POST A NEW LISTING", new_listing_path, class: "btn btn-default new-listing-btn pull-right" %>
			</div>
			<%- for @listing in @listings %>
				<div class="item col-xs-12">
					<span class="list-right animated fadeInRight"></span>
					<span class="edit pull-left">
						<%= link_to edit_listing_path(@listing), class: "edit-btn pull-left" do %>
							<i class="glyphicon glyphicon-pencil"></i>
						<% end %>
						&emsp;
						<%= link_to listing_path(@listing.id), :confirm => "Are you sure you want to delete this listing?", :method => :delete do %>
							<i class="glyphicon trash-icon"></i>
						<% end %>
					</span>
					<div class="image pull-left">
						<% if @listing.images.present? %>
							<%= link_to "", listing_path(@listing.id), class: "thumb-listing", style: "background-image: url('#{image_url(@listing.images[0].image)}'); -webkit-border-radius: 20px !important; border-radius: 20px !important"  %>
						<% else %>
							<%= image_tag image_url("no_pic.jpg"), class: "img-responsive" %>
						<% end %>
					</div>
					<div class="information">
						<p class="info-title">
							<%= link_to @listing.title.titleize, listing_path(@listing.id) %>
						</p>
						<p class="info-description">
							<%= @listing.info %>
						</p>
					</div>
					<div class="price">
						<%= number_to_currency(@listing.price, :locale => 'en_us', :precision => 0) %>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>