config/routes.rb
Tapsell::Application.routes.draw do

  get "offers/listings/:id" => "offers#confirm_listings_page", as: 'new_offer'
  post "offers/listings/:id" => "offers#create_new_offer", as: 'offer'
  get "offers/listings/:id/confirmation" => "offers#offer_confirmation", as: 'offer_confirmation'

  get "users/message/accept/:id" => "messages#accept_offer_message", as: 'accept_offer_message'
  get "users/message/decline/:id" => "messages#decline_offer_message", as: 'decline_offer_message'

  get "users/:id/message" => "messages#index", as: 'messages'
  get "update_msg_chain" => "messages#update_msg_chain", as: 'update_msg_chain'
  post "users/:id/message" => "messages#create", as: 'new_message'
  
  get "listings/search" => "listings#search_listings", as: 'search_listings'
  get "listings/:id/confirm" => "listings#confirm_listing", as: 'confirm_listing'
  post "listings/:id/direct_message" => "listings#direct_message", as: 'direct_message'
  get "newest_listings" => "listings#newest_listings", as: 'newest_listings'
  get "oldest_listings" => "listings#oldest_listings", as: 'oldest_listings'
  get "low_price_listings" => "listings#low_price_listings", as: 'low_price_listings'
  get "high_price_listings" => "listings#high_price_listings", as: 'high_price_listings'
  get "all_listings" => "listings#all_listings", as: 'all_listings'
  get "book_listings" => "listings#book_listings", as: 'book_listings'
  get "apparel_listings" => "listings#apparel_listings", as: 'apparel_listings'
  get "electronic_listings" => "listings#electronic_listings", as: 'electronic_listings'
  get "home_listings" => "listings#home_listings", as: 'home_listings'
  get "ticket_listings" => "listings#ticket_listings", as: 'ticket_listings'
  get "other_listings" => "listings#other_listings", as: 'other_listings'

  get "users/:id/user_settings" => "user_settings#index", as: 'user_settings'
  post "users/:id/user_settings" => "credit_cards#create_card", as: 'create_card'

  get "users/:id/view" => "users#show_public", as: 'public_profile'

  post "users/:id/photo" => "users#new_photo", as: 'new_user_photo'

  get "users/:id/listings" => "listings#show_my_listings", as: 'my_listings'

  get "users/:id/dashboard" => "dashboard#show", as: 'dashboard'

  get "reviews/:id" => "reviews#new", as: 'new_review'
  post "reviews/:id" => "reviews#create", as: 'review'

  match '/sign-up', to: 'users#new', via: 'get'
  match 'sign-in', to: 'sessions#new', via: 'get', as: 'sign_in'
  match '/sign-out', to: 'sessions#destroy', via: 'delete'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets
  resources :listings
  resources :credit_cards

  get "/tutorial" => "tutorial_pages#landing", as: 'tutorial_landing'
  get "/tutorial/sign_up" => "tutorial_pages#sign_up", as: 'tutorial_sign_up'
  post "/tutorial/create" => "tutorial_pages#create", as: 'tutorial_create_user'
  get "/tutorial/1" => "tutorial_pages#step_one", as: 'tutorial_step_one'
  get "/tutorial/2" => "tutorial_pages#step_two", as: 'tutorial_step_two'
  get "/tutorial/3" => "tutorial_pages#step_three", as: 'tutorial_step_three'
  get "/tutorial/4" => "tutorial_pages#step_four", as: 'tutorial_step_four'
  get "/tutorial/5" => "tutorial_pages#step_five", as: 'tutorial_step_five'
  get "/tutorial/6" => "tutorial_pages#step_six", as: 'tutorial_step_six'
  get "/tutorial/finish" => "tutorial_pages#finish", as: 'tutorial_finish'
  get "/tutorial/get_certificate" => "tutorial_pages#get_certificate", as: 'tutorial_get_cert'

  root :to => 'listings#index'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/launch', to: 'marketing_emails#launch', via: 'get'
  match '/team', to: 'static_pages#team', via: 'get'
  match '/jobs', to: 'static_pages#jobs', via: 'get'
  match '/blog', to: 'static_pages#blog', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/faq', to: 'static_pages#faq', via: 'get'
  match '/buyer_faq', to: 'static_pages#buyer_faq', via: 'get'
  match '/terms', to: 'static_pages#terms', via: 'get'
  match '/privacy', to: 'static_pages#privacy', via: 'get'
  match '/buyer_guarantee', to: 'static_pages#buyer_guarantee', via: 'get'

  namespace :api do
    post 'users' => 'users#create'
    get 'users/profile' => 'users#index'
    post 'users/profile/edit' => 'users#update'
    get 'users/:user_id' => 'users#show'
    post 'sessions' => 'sessions#create'
    delete 'sessions' => 'sessions#destroy'
    get 'listings' => 'listings#index'
    post 'listings' => 'listings#create'
    delete 'listings' => 'listings#destroy'
    get 'messages' => 'messages#index'
    post 'messages' => 'messsages#create'
    get 'messages/:msg_chain_id/chain' => 'messages#messages_in_chain',
      :msg_chain_id => /[\w.-]+/
  end

end

app/controllers/tutorial_pages_controller.rb
class TutorialPagesController < ApplicationController
  layout "no_format_tutorial_pages", except: [:sign_up]

  def landing
  end

  def sign_up
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      store_location
      @user.remember_token = User.encrypt(User.new_remember_token)
      sign_in @user
      flash[:success] = "Welcome to Tapsell!"
      redirect_to tutorial_step_one_path
      Notifier.delay.send_welcome_email(@user)
    else
      flash[:notice] = 'That email / password combination is invalid, please try again.'
      redirect_to tutorial_sign_up_path
    end
  end

  def step_one
    flash.delete(:notice)
  end

  def step_two
  end

  def step_three
  end

  def step_four
  end

  def step_five
  end

  def step_six
  end

  def finish
  end

  def get_certificate
    Notifier.send_launch_email(current_user).deliver
    flash[:success] = 'Congratulations! The certificate was sent to your email!'
    redirect_to tutorial_finish_path
  end

private

  def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :bio)
  end

end

app/helpers/tutorial_pages_helper.rb
module TutorialPagesHelper
end

app/views/tutorial_pages/finish.html.erb
<body>
<style type="text/css" media="all">
@import url(http://fonts.googleapis.com/css?family=Arvo:400,700,400italic,700italic);
</style>

<style>
/* Reset body padding and margins */
body
{
    margin: 0 !important;
    padding: 0 !important;
}

/* Make Header Sticky */
#header_container
{
    background: transparent !important;
    border: 0px solid #666 !important;
    height: 70px !important;
    left: 0 !important;
    position: fixed !important;
    width: 100% !important;
    top: 0 !important;
	padding-top: 35px !important;
}

#header_container 
      { 
        position:fixed !important;
        top:0px !important;
        left:0px !important;
        z-index:1000 !important;
       }

 #header{
      z-index:1001 !important;
      }
	  
#header
{
    line-height: 60px !important;
    margin: 10 auto !important;
    width: 940px !important;
    font-size: 26px !important;
    color: #f5f5f5 !important;
    line-height: 28px !important;
    margin-bottom: 14px !important;
	align: center !important;
	margin: 0 auto !important;
}

/* CSS for the content of page. I am giving top and bottom 
   padding of 80px to make sure the header and footer 
   do not overlap the content. */
#container
{
    margin: 0 auto !important;
    overflow: auto !important;
    padding: 80px 0 !important;
    width: 940px !important;
}

#content
{
	padding-top: 20px !important;
}


</style>


<!-- BEGIN: Sticky Header -->
<div id="header_container">
    <div id="header" style="text-align: center !important;">
        <table width="100%">
        <tr>
        <td width="50%" style="text-align: left !important;">
        <img src="http://www.jacquelinechen.com/tapsell/tutorial/Tapsell_Logo.png" height="60%" width="auto"/>
        </td>
        <td width="50%" style="text-align: right; !important">
        <a href="#anchor" style="text-decoration: none !important; color: #9c9c9 !important;"><p style="font-family: Helvetica, Arial, sans-serif !important; color: #9C9C9C !important; font-size: 0.5em !important; -webkit-font-smoothing: antialiased !important; "></p></a>
        </td>        
        </tr>
        
        <tr>
        <td width="100%">
        <style type="text/css">
		.imagesprite {
display: block;
width: 300px;
height: 61px;
background:url(http://www.jacquelinechen.com/tapsell/tutorial/getcertificate_sprite.png) no-repeat 0 0;
overflow: auto;
text-indent: -15000px;
font-size: 0px;
line-height: 0px;
}
 
.imagesprite:hover {
background-position: 0 -61px;
}
 
.imagesprite:active {
background-position: 0 -300px;
}
	
	</style>
        </td>
        </tr>
        </table>
    </div>
</div>
<!-- END: Sticky Header -->
<div id="container">

	<!--First section of content-->
    <div id="content" style="padding-bottom: 12% !important; text-align: center;">
    <table width="100%" style="padding-top: 2% !important;">
    <tr>
    <td width="100%" style="text-align: center !important;">
    <img src="http://www.jacquelinechen.com/tapsell/tutorial/double_headshot.png" width="340px" height="auto"/>
    <p style="font-family: 'Arvo', Helvetica, Arial, sans-serif !important; color: #878787 !important; font-size: 2.5em !important; -webkit-font-smoothing: antialiased !important;">
       Now Bryant is $80 richer, and Rebecca is snorkeling somewhere off the Australian coast.</p>
<p style="font-family: 'Arvo', Helvetica, Arial, sans-serif !important; color: #878787 !important; font-size: 1.5em !important; -webkit-font-smoothing: antialiased !important;">
       That's it! Now you know a little bit more about Tapsell. Click below to get your completion certificate (aka your ticket for free Phil's!).</p>
       
    <p style="font-family: Helvetica, Arial, sans-serif !important; color: #878787 !important; font-size: 1.2em !important; letter-spacing: 0.05em !important; -webkit-font-smoothing: antialiased !important;">
    The launch event will take place on Tuesday, May 27th @ Library Walk, from 8am to 5pm. See you there!
    </p>
    <%= bootstrap_flash %>
    <%= link_to tutorial_get_cert_path do %>
        <img src="http://www.jacquelinechen.com/Finish_before.png" onmouseover="this.src='http://www.jacquelinechen.com/Finish_after.png'" onmouseout="this.src='http://www.jacquelinechen.com/Finish_before.png'"  />
    <% end %>
    </td>
    </tr>
    </table>
    </div>
    </div>
    
</div>

</body>

app/views/tutorial_pages/sign_up.html.erb
<% provide(:title, 'Join') %>
<%= content_for :stylesheet_contents do %>
  <%= stylesheet_link_tag "sessions" %>
<% end %>

<div class="col-xs-12">
  <div class="container">
    <div class="title-container">
      <h1 class="login-title text-center">Sign up to complete the tutorial.</h1>
      <h2 class="login-subtitle text-center">It takes less than a minute. </h2>


    <div class="registration-container center-block">
      <%= form_for(@user, as: :user, url: tutorial_create_user_path(@user), html: {method: :post, class: "col-xs-12", role: "form"}) do |f| %>

        <div class="form-group">
          <%= f.text_field :first_name, class: "form-control", placeholder: "First Name", :required => true %>
        </div>
        <div class="form-group">
          <%= f.text_field :last_name, class: "form-control", placeholder: "Last Name", :required => true %>
        </div>
        <div class="form-group">
          <%= f.text_field :email, class: "form-control", placeholder: "Email", :required => true %>
        </div>

        <div class="form-group">
          <%= f.password_field :password, class: "form-control password-input", placeholder: "Password", :required => true %>
        </div>

        <div class="form-group text-center">
          <%= f.submit "GET ME STARTED", class: "btn btn-large btn-primary" %>
        </div>

      <% end %>

    </div>

  </div>

</div>

app/views/tutorial_pages/step_five.html.erb
<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<title>Tapsell Launches @ UCSD</title>
</head>

<body>
<style type="text/css" media="all">
@import url(http://fonts.googleapis.com/css?family=Arvo:400,700,400italic,700italic);
</style>

<style>
/* Reset body padding and margins */
body
{
    margin: 0 !important;
    padding: 0 !important;
	overflow: auto;
}

/* Make Header Sticky */
#header_container
{
    background: #FFFFFF !important;
    border: 0px solid #666 !important;
    height: 70px !important;
    left: 0 !important;
    position: fixed !important;
    width: 100% !important;
    top: 0 !important;
	padding-top: 35px !important;
}

#header_container 
      { 
        position:fixed !important;
        top:0px !important;
        left:0px !important;
        z-index:1000 !important;
       }

 #header{
      z-index:1001 !important;
      }
	  
#header
{
    line-height: 60px !important;
    margin: 10 auto !important;
    width: 940px !important;
    font-size: 26px !important;
    color: #f5f5f5 !important;
    line-height: 28px !important;
    margin-bottom: 14px !important;
	align: center !important;
	margin: 0 auto !important;
}

/* CSS for the content of page. I am giving top and bottom 
   padding of 80px to make sure the header and footer 
   do not overlap the content. */
#container
{
    margin: 0 auto !important;
    overflow: auto !important;
    padding: 80px 0 !important;
    width: 940px !important;
}

#content
{
	padding-top: 20px !important;
}


</style>


<!-- BEGIN: Sticky Header -->
<div id="header_container">
    <div id="header" style="text-align: center !important;">
        <table width="100%">
        <tr>
        <td width="50%" style="text-align: left !important;">
        <img src="http://www.jacquelinechen.com/tapsell/tutorial/Tapsell_Logo.png" height="60%" width="auto"/>
        </td>
        <td width="50%" style="text-align: right; !important">
        <a href="#anchor" style="text-decoration: none !important; color: #9c9c9 !important;"><p style="font-family: Helvetica, Arial, sans-serif !important; color: #9C9C9C !important; font-size: 0.5em !important; -webkit-font-smoothing: antialiased !important; ">STEP 5 OF 6</p></a>
        </td>        
        </tr>
        

        </table>
    </div>
</div>
<!-- END: Sticky Header -->
<div id="container">

	<!--First section of content-->
    <div id="content" style="text-align: center;">
    <table width="100%" style="padding-top: 7% !important;">
    <tr>
       
    <td width="40%" style="text-align: center !important; padding-right: 20px;">
    <img src="http://www.jacquelinechen.com/tapsell/tutorial/bryant_headshot2.png" width="170px" height="auto"/>
    <p style="font-family: 'Arvo', Helvetica, Arial, sans-serif !important; color: #878787 !important; font-size: 2.0em !important; -webkit-font-smoothing: antialiased !important;">
       He accepts Rebecca's offer.</p>     
    </td>
     <td width="60%" style="padding-left: 30px;">
<%= link_to tutorial_step_six_path do %>
<img id="step5" src="http://www.jacquelinechen.com/tapsell/tutorial/step5_small.png" border="0" width="625" height="445" orgWidth="625" orgHeight="445" usemap="#image-maps-2014-05-21-013822" alt="" />
<% end %>
<map name="image-maps-2014-05-21-013822" id="ImageMapsCom-image-maps-2014-05-21-013822">
<area shape="rect" coords="623,443,625,445" alt="step5" style="outline:none;" title="Image Map" href="http://www.image-maps.com/index.php?aff=mapped_users_0" />
</map>

    </td>
    </tr>
    </table>
    
    </div>
    </div>
    
    
    
</div>

</body>
</html>

app/views/tutorial_pages/step_four.html.erb
<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<title>Tapsell Launches @ UCSD</title>
</head>

<body>
<style type="text/css" media="all">
@import url(http://fonts.googleapis.com/css?family=Arvo:400,700,400italic,700italic);
</style>

<style>
/* Reset body padding and margins */
body
{
    margin: 0 !important;
    padding: 0 !important;
	overflow: auto;
}

/* Make Header Sticky */
#header_container
{
    background: #FFFFFF !important;
    border: 0px solid #666 !important;
    height: 70px !important;
    left: 0 !important;
    position: fixed !important;
    width: 100% !important;
    top: 0 !important;
	padding-top: 35px !important;
}

#header_container 
      { 
        position:fixed !important;
        top:0px !important;
        left:0px !important;
        z-index:1000 !important;
       }

 #header{
      z-index:1001 !important;
      }
	  
#header
{
    line-height: 60px !important;
    margin: 10 auto !important;
    width: 940px !important;
    font-size: 26px !important;
    color: #f5f5f5 !important;
    line-height: 28px !important;
    margin-bottom: 14px !important;
	align: center !important;
	margin: 0 auto !important;
}

/* CSS for the content of page. I am giving top and bottom 
   padding of 80px to make sure the header and footer 
   do not overlap the content. */
#container
{
    margin: 0 auto !important;
    overflow: auto !important;
    padding: 80px 0 !important;
    width: 940px !important;
}

#content
{
	padding-top: 20px !important;
}


</style>


<!-- BEGIN: Sticky Header -->
<div id="header_container">
    <div id="header" style="text-align: center !important;">
        <table width="100%">
        <tr>
        <td width="50%" style="text-align: left !important;">
        <img src="http://www.jacquelinechen.com/tapsell/tutorial/Tapsell_Logo.png" height="60%" width="auto"/>
        </td>
        <td width="50%" style="text-align: right; !important">
        <a href="#anchor" style="text-decoration: none !important; color: #9c9c9 !important;"><p style="font-family: Helvetica, Arial, sans-serif !important; color: #9C9C9C !important; font-size: 0.5em !important; -webkit-font-smoothing: antialiased !important; ">STEP 4 OF 6</p></a>
        </td>        
        </tr>
        

        </table>
    </div>
</div>
<!-- END: Sticky Header -->
<div id="container">

	<!--First section of content-->
    <div id="content" style="text-align: center;">
    <table width="100%" style="padding-top: 2% !important;">
    <tr>
   
    <td width="60%">
<%= link_to tutorial_step_five_path do %>
<img id="step4" src="http://www.jacquelinechen.com/tapsell/tutorial/step4_small.png" border="0" width="576" height="600" orgWidth="576" orgHeight="600" usemap="#image-maps-2014-05-21-012727" alt="" />
<% end %>
<map name="image-maps-2014-05-21-012727" id="ImageMapsCom-image-maps-2014-05-21-012727">
<area shape="rect" coords="574,598,576,600" alt="step4" style="outline:none;" title="Image Map" href="http://www.image-maps.com/index.php?aff=mapped_users_0" />
</map>
<td width="40%" style="text-align: center !important; padding-left: 30px;">
    <img src="http://www.jacquelinechen.com/tapsell/tutorial/bryant_headshot2.png" width="170px" height="auto"/>
    <p style="font-family: 'Arvo', Helvetica, Arial, sans-serif !important; color: #878787 !important; font-size: 2.0em !important; -webkit-font-smoothing: antialiased !important;">
       Bryant checks his inbox and finds that he has an offer. Sweet!</p>     
    </td>

    </td>
    </tr>
    </table>
    
    </div>
    </div>
   
    
</div>

</body>
</html>

app/views/tutorial_pages/step_one.html.erb
<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<title>Tapsell Launches @ UCSD</title>
</head>

<body>
<style type="text/css" media="all">
@import url(http://fonts.googleapis.com/css?family=Arvo:400,700,400italic,700italic);
</style>

<style>
/* Reset body padding and margins */
body
{
    margin: 0 !important;
    padding: 0 !important;
	overflow: auto;
}

/* Make Header Sticky */
#header_container
{
    background: #FFFFFF !important;
    border: 0px solid #666 !important;
    height: 70px !important;
    left: 0 !important;
    position: fixed !important;
    width: 100% !important;
    top: 0 !important;
	padding-top: 35px !important;
}

#header_container 
      { 
        position:fixed !important;
        top:0px !important;
        left:0px !important;
        z-index:1000 !important;
       }

 #header{
      z-index:1001 !important;
      }
	  
#header
{
    line-height: 60px !important;
    margin: 10 auto !important;
    width: 940px !important;
    font-size: 26px !important;
    color: #f5f5f5 !important;
    line-height: 28px !important;
    margin-bottom: 14px !important;
	align: center !important;
	margin: 0 auto !important;
}

/* CSS for the content of page. I am giving top and bottom 
   padding of 80px to make sure the header and footer 
   do not overlap the content. */
#container
{
    margin: 0 auto !important;
    overflow: auto !important;
    padding: 80px 0 !important;
    width: 940px !important;
}

#content
{
	padding-top: 20px !important;
}


</style>


<!-- BEGIN: Sticky Header -->
<div id="header_container">
    <div id="header" style="text-align: center !important;">
        <table width="100%">
        <tr>
        <td width="50%" style="text-align: left !important;">
        <img src="http://www.jacquelinechen.com/tapsell/tutorial/Tapsell_Logo.png" height="60%" width="auto"/>
        </td>
        <td width="50%" style="text-align: right; !important">
        <a href="#anchor" style="text-decoration: none !important; color: #9c9c9 !important;"><p style="font-family: Helvetica, Arial, sans-serif !important; color: #9C9C9C !important; font-size: 0.5em !important; -webkit-font-smoothing: antialiased !important; ">STEP 1 OF 6</p></a>
        </td>        
        </tr>
        

        </table>
    </div>
</div>
<!-- END: Sticky Header -->
<div id="container">

	<!--First section of content-->
    <div id="content" style="text-align: center;">
    <table width="100%" style="padding-top: 2% !important;">
    <tr>
    <td width="40%" style="text-align: center !important;">
    <img src="http://www.jacquelinechen.com/tapsell/tutorial/bryant_headshot2.png" width="170px" height="auto"/>
    <p style="font-family: 'Arvo', Helvetica, Arial, sans-serif !important; color: #878787 !important; font-size: 2.0em !important; -webkit-font-smoothing: antialiased !important;">
       Bryant is looking to sell his GoPro, so he posts a listing.</p>     
    </td>
    <td width="60%">
<%= link_to tutorial_step_two_path do %>
<img id="step1" src="http://www.jacquelinechen.com/tapsell/tutorial/step1_small.png" border="0" width="469" height="600" orgWidth="469" orgHeight="600" usemap="#image-maps-2014-05-21-010526" alt="" />
<% end %>
<map name="image-maps-2014-05-21-010526" id="ImageMapsCom-image-maps-2014-05-21-010526">
<area shape="rect" coords="467,598,469,600" alt="step1" style="outline:none;" title="Image Map" href="http://www.image-maps.com/index.php?aff=mapped_users_0" />
</map>

    </td>
    </tr>
    </table>
    
    </div>
    </div>
    
    
    
</div>

</body>
</html>

app/views/tutorial_pages/step_three.html.erb
<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<title>Tapsell Launches @ UCSD</title>
</head>

<body>
<style type="text/css" media="all">
@import url(http://fonts.googleapis.com/css?family=Arvo:400,700,400italic,700italic);
</style>

<style>
/* Reset body padding and margins */
body
{
    margin: 0 !important;
    padding: 0 !important;
	overflow: auto;
}

/* Make Header Sticky */
#header_container
{
    background: #FFFFFF !important;
    border: 0px solid #666 !important;
    height: 70px !important;
    left: 0 !important;
    position: fixed !important;
    width: 100% !important;
    top: 0 !important;
	padding-top: 35px !important;
}

#header_container 
      { 
        position:fixed !important;
        top:0px !important;
        left:0px !important;
        z-index:1000 !important;
       }

 #header{
      z-index:1001 !important;
      }
	  
#header
{
    line-height: 60px !important;
    margin: 10 auto !important;
    width: 940px !important;
    font-size: 26px !important;
    color: #f5f5f5 !important;
    line-height: 28px !important;
    margin-bottom: 14px !important;
	align: center !important;
	margin: 0 auto !important;
}

/* CSS for the content of page. I am giving top and bottom 
   padding of 80px to make sure the header and footer 
   do not overlap the content. */
#container
{
    margin: 0 auto !important;
    overflow: auto !important;
    padding: 80px 0 !important;
    width: 940px !important;
}

#content
{
	padding-top: 20px !important;
}


</style>


<!-- BEGIN: Sticky Header -->
<div id="header_container">
    <div id="header" style="text-align: center !important;">
        <table width="100%">
        <tr>
        <td width="50%" style="text-align: left !important;">
        <img src="http://www.jacquelinechen.com/tapsell/tutorial/Tapsell_Logo.png" height="60%" width="auto"/>
        </td>
        <td width="50%" style="text-align: right; !important">
        <a href="#anchor" style="text-decoration: none !important; color: #9c9c9 !important;"><p style="font-family: Helvetica, Arial, sans-serif !important; color: #9C9C9C !important; font-size: 0.5em !important; -webkit-font-smoothing: antialiased !important; ">STEP 3 OF 6</p></a>
        </td>        
        </tr>
        

        </table>
    </div>
</div>
<!-- END: Sticky Header -->
<div id="container">

	<!--First section of content-->
    <div id="content" style="text-align: center;">
    <table width="100%" style="padding-top: 8% !important;">
    <tr>
    <td width="40%" style="text-align: center !important;">
    <img src="http://www.jacquelinechen.com/tapsell/tutorial/rebecca_headshot2.png" width="170px" height="auto"/>
    <p style="font-family: 'Arvo', Helvetica, Arial, sans-serif !important; color: #878787 !important; font-size: 2.0em !important; -webkit-font-smoothing: antialiased !important;">
       She decides to make an offer of $80.00 for it.</p>     
    </td>
    <td width="60%" style="padding-left: 40px;">
<%= link_to tutorial_step_four_path do %>
<img id="step3" src="http://www.jacquelinechen.com/tapsell/tutorial/step3_small.png" border="0" width="625" height="451" orgWidth="625" orgHeight="451" usemap="#image-maps-2014-05-21-012228" alt="" />
<% end %>
<map name="image-maps-2014-05-21-012228" id="ImageMapsCom-image-maps-2014-05-21-012228">
<area shape="rect" coords="623,449,625,451" alt="step3" style="outline:none;" title="Image Map" href="http://www.image-maps.com/index.php?aff=mapped_users_0" />
</map>

    </td>
    </tr>
    </table>
    
    </div>
    </div>

    
</div>

</body>
</html>