config/routes.rb
Tapsell::Application.routes.draw do

  get "offers/listings/:id" => "offers#confirm_listings_page", as: 'new_offer'
  post "offers/listings/:id" => "offers#create_new_offer", as: 'offer'
  get "offers/listings/:id/confirmation" => "offers#offer_confirmation", as: 'offer_confirmation'

  get "users/message/accept/:id" => "messages#accept_offer_message", as: 'accept_offer_message'
  get "users/message/decline/:id" => "messages#decline_offer_message", as: 'decline_offer_message'

  get "users/:id/message" => "messages#index", as: 'messages'
  get "update_msg_chain" => "messages#update_msg_chain", as: 'update_msg_chain'
  post "users/:id/message" => "messages#create", as: 'new_message'
  
  get "listings/search" => "listings#search_listings", as: 'search_listings'
  get "listings/:id/confirm" => "listings#confirm_listing", as: 'confirm_listing'
  post "listings/:id/direct_message" => "listings#direct_message", as: 'direct_message'
  get "newest_listings" => "listings#newest_listings", as: 'newest_listings'
  get "oldest_listings" => "listings#oldest_listings", as: 'oldest_listings'
  get "low_price_listings" => "listings#low_price_listings", as: 'low_price_listings'
  get "high_price_listings" => "listings#high_price_listings", as: 'high_price_listings'
  get "all_listings" => "listings#all_listings", as: 'all_listings'
  get "book_listings" => "listings#book_listings", as: 'book_listings'
  get "apparel_listings" => "listings#apparel_listings", as: 'apparel_listings'
  get "electronic_listings" => "listings#electronic_listings", as: 'electronic_listings'
  get "home_listings" => "listings#home_listings", as: 'home_listings'
  get "ticket_listings" => "listings#ticket_listings", as: 'ticket_listings'
  get "other_listings" => "listings#other_listings", as: 'other_listings'

  get "users/:id/user_settings" => "user_settings#index", as: 'user_settings'
  post "users/:id/user_settings" => "credit_cards#create_card", as: 'create_card'

  get "users/:id/view" => "users#show_public", as: 'public_profile'

  post "users/:id/photo" => "users#new_photo", as: 'new_user_photo'

  get "users/:id/listings" => "listings#show_my_listings", as: 'my_listings'

  get "users/:id/dashboard" => "dashboard#show", as: 'dashboard'

  get "reviews/:id" => "reviews#new", as: 'new_review'
  post "reviews/:id" => "reviews#create", as: 'review'

  match '/sign-up', to: 'users#new', via: 'get'
  match 'sign-in', to: 'sessions#new', via: 'get', as: 'sign_in'
  match '/sign-out', to: 'sessions#destroy', via: 'delete'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets
  resources :listings
  resources :credit_cards

  get "/tutorial" => "tutorial_pages#landing", as: 'tutorial_landing'
  get "/tutorial/sign_up" => "tutorial_pages#sign_up", as: 'tutorial_sign_up'
  post "/tutorial/create" => "tutorial_pages#create", as: 'tutorial_create_user'
  get "/tutorial/1" => "tutorial_pages#step_one", as: 'tutorial_step_one'
  get "/tutorial/2" => "tutorial_pages#step_two", as: 'tutorial_step_two'
  get "/tutorial/3" => "tutorial_pages#step_three", as: 'tutorial_step_three'
  get "/tutorial/4" => "tutorial_pages#step_four", as: 'tutorial_step_four'
  get "/tutorial/5" => "tutorial_pages#step_five", as: 'tutorial_step_five'
  get "/tutorial/6" => "tutorial_pages#step_six", as: 'tutorial_step_six'
  get "/tutorial/finish" => "tutorial_pages#finish", as: 'tutorial_finish'
  get "/tutorial/get_certificate" => "tutorial_pages#get_certificate", as: 'tutorial_get_cert'

  root :to => 'listings#index'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/launch', to: 'marketing_emails#launch', via: 'get'
  match '/team', to: 'static_pages#team', via: 'get'
  match '/jobs', to: 'static_pages#jobs', via: 'get'
  match '/blog', to: 'static_pages#blog', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/faq', to: 'static_pages#faq', via: 'get'
  match '/buyer_faq', to: 'static_pages#buyer_faq', via: 'get'
  match '/terms', to: 'static_pages#terms', via: 'get'
  match '/privacy', to: 'static_pages#privacy', via: 'get'
  match '/buyer_guarantee', to: 'static_pages#buyer_guarantee', via: 'get'

  namespace :api do
    post 'users' => 'users#create'
    get 'users/profile' => 'users#index'
    post 'users/profile/edit' => 'users#update'
    get 'users/:user_id' => 'users#show'
    post 'sessions' => 'sessions#create'
    delete 'sessions' => 'sessions#destroy'
    get 'listings' => 'listings#index'
    post 'listings' => 'listings#create'
    delete 'listings' => 'listings#destroy'
    get 'messages' => 'messages#index'
    post 'messages' => 'messsages#create'
    get 'messages/:msg_chain_id/chain' => 'messages#messages_in_chain',
      :msg_chain_id => /[\w.-]+/
  end

end

app/models/offer.rb
class Offer < ActiveRecord::Base

  STATUS_WAITING_FOR_SELLER_RESPONSE = "waiting for seller response"
  STATUS_DENIED = "denied"
  STATUS_ACCEPTED = "accepted"
  STATUS_HALTED = "halted"
  STATUS_TRANSACTION_SUCCESSFUL = "transaction successful"
  STATUS_TRANSACTION_FAILED = "transaction failed"

  belongs_to :listing
  belongs_to :message_chain
  belongs_to :seller, :class_name => "User", :foreign_key => "seller_id"
  belongs_to :buyer, :class_name => "User", :foreign_key => "buyer_id"
  belongs_to :credit_card

  has_many :reviews

  def self.create_offer!(buyer, listing, cc=nil, price=nil)
    if price.present?
      p = price
    else
      p = listing.price
    end

    # if cc.present?
    #   credit_card = cc
    # else
    #   credit_card = buyer.default_credit_card
    # end

    offer = Offer.create!(
      seller: listing.seller,
      listing: listing,
      buyer: buyer,
      price: p,
      status: STATUS_WAITING_FOR_SELLER_RESPONSE,
      credit_card: nil,
    )

    offer
  end

  def self.accept_offer(seller, offer)
    raise "Seller does not own offer" if !seller.offers_as_seller.include? offer

    offer.status = STATUS_ACCEPTED
    offer.listing.sold_to(offer)
    offer.save!
    # TODO: this must be handled in two different flows, one where
    # user has a bank account, and thus we can just use escrow with braintree,
    # and one where we send the funds to our account to act as escrow if they
    # have not yet created a bank account (This method costs $0.25).
    # tapsell fee is price * %3.5
    # total = offer.price * 100 +  offer.price * 0.035 * 100
    # begin
    #   Stripe::Charge.create(
    #     amount: total.to_i,
    #     currency: "usd",
    #     customer: offer.buyer.stripe_customer_id,
    #     card: offer.credit_card.stripe_id,
    #     description: "Charge for seller with id #{seller.id} and offer id #{offer.id} for #{total}",
    #     statement_description: "Tapsell",
    #   )
    # rescue => e
    #   raise "Credit card charge error: #{e.message}"
    # end
  end

  def self.complete_offer(offer)
    offer.status = STATUS_TRANSACTION_SUCCESSFUL
    offer.save!

    begin
      Stripe::Transfer.create(
        amount: offer.price * 100,
        currency: "usd",
        recipient: offer.seller.default_recipient.stripe_id,
        description: "Tapsell",
      )
    rescue => e
      raise "Complete transfer error: #{e.message}"
    end
  end

  def cancel
    self.status = STATUS_DENIED

    # remove timers associated with offer
    Delayed::Job.where(queue: "offer_id$$$#{self.id}").destroy_all
    save
  end

  def set_accept_timers
    self.start_time_for_accepting = DateTime.now
    self.target_time_for_accepting = 1.day.from_now.end_of_day
    self.save!
  end

  def set_delivery_timers
    self.start_time_for_delivery = DateTime.now
    self.target_time_for_delivery = 3.days.from_now.end_of_day
    self.save!
  end

  def initialize_accept_timer
    # Initialize timers on offer, check status in a day.
    self.set_accept_timers

    Offer.delay(run_at: 1.day.from_now.end_of_day, queue: "offer_id$$$#{self.id}").accept_timer_did_finish(self.id)
  end

  def initialize_delivery_timer
    # Initialize timers on offer, check status in three days.
    self.set_delivery_timers

    Offer.delay(run_at: 3.days.from_now.end_of_day, queue: "offer_id$$$#{self.id}").delivery_timer_did_finish(self.id)
  end

  def self.delivery_timer_did_finish(offer_id)
    offer = Offer.find(offer_id)

    # If the offer is halted, then just return.
    return if offer.status == STATUS_HALTED

    # Otherwise, the offer is successful, send success message, send reviews
    offer.status = STATUS_TRANSACTION_SUCCESSFUL
    offer.save
    review_to_buyer = Review.create(reviewer: offer.buyer, reviewee: offer.seller, offer: offer)
    review_to_seller = Review.create(reviewer: offer.seller, reviewee: offer.buyer, offer: offer)
    Notifier.delay.send_review_email(review_to_buyer)
    Notifier.delay.send_review_email(review_to_seller)
  end

  def self.accept_timer_did_finish(offer_id)
    offer = Offer.find(offer_id)

    # If the offer has ben acted on, then ignore.
    return if offer.status != STATUS_WAITING_FOR_SELLER_RESPONSE

    # If it hasn't, then decline the offer and send a declining message.
    offer.cancel
    MessageChain.send_message(offer.seller.id, offer.listing.id, "#{offer.seller.first_name.titleize} did not reply to the offer in time." , Message::TYPE_DEFAULT, offer.message_chain.id, nil)
  end

end

app/controllers/offers_controller.rb
class OffersController < ApplicationController

  def confirm_listings_page
    @listing = Listing.find(params[:id])
    @offer_price = params[:offer_price]
    if signed_in?
      render '_confirm_offer'
    else
      @user = User.new
      render '_sign_in_to_offer'
      store_location
    end
  end

  def create_new_offer
    @user = current_user
    # @credit_card = get_chosen_credit_card
    # if @credit_card.nil?
    #   @listing = Listing.find(params[:listing_id].to_i)
    #   @offer_price = params[:offer_price].to_f
    #   flash[:notice] = 'There was a problem creating the offer.  Please double-check your credit card information and try again.'
    #   render '_confirm_offer'
    #   return
    # end

    create_authorization
    @offer = Offer.create_offer!(current_user, Listing.find(params[:listing_id]), @credit_card, params[:offer_price].to_f)
    buyer = @offer.buyer
    seller = @offer.seller
    Notifier.delay.send_offer_received_email(seller, @offer)
    Notifier.delay.send_offer_confirmation_email(buyer, @offer)
    redirect_to offer_confirmation_path({:offer_id => @offer.id, :message => params[:message]})
  end

  def offer_confirmation
    @offer = Offer.find(params[:offer_id])
    @listing = @offer.listing

    # If the offer created is successful, delete notice messages and initialize timer/send inquiry message.
    # Create offer message to seller, then add additional message.
    flash.delete(:notice)
    MessageChain.send_message(current_user.id, @listing.id, "#{current_user.first_name.titleize} #{current_user.last_name.titleize} offered #{ActionController::Base.helpers.number_to_currency(@offer.price)} for #{@listing.title}." , Message::TYPE_OFFER, nil, @offer)
    if params[:message].present?
      MessageChain.send_message(current_user.id, @listing.id, params[:message], Message::TYPE_DEFAULT, nil, nil)
    end

    @offer.initialize_accept_timer
  end

  def get_chosen_credit_card
    credit_card = nil
    # if there is a chosen card id, use that
    if params[:chosen_card_id].present?
      credit_card = CreditCard.find(params[:chosen_card_id].to_i)
    else
      # otherwise, verify form stuff and create card
      begin
        credit_card = CreditCard.create_cc(current_user, params[:number], params[:exp_month].to_i, params[:exp_year].to_i, params[:cvc])
      rescue
        return nil
      end
    end
    return credit_card
  end

  def create_authorization
    # Authorize credit cards here
  end
  
end

app/views/offers/_confirm_offer.html.slim
= content_for :javascript_contents do
  = javascript_include_tag "offers"

= content_for :stylesheet_contents do
  = stylesheet_link_tag "offers"

.container.marg-top-125
  .col-xs-8.box-container.left-container
    = form_tag offer_path, method: "post", id: "payment-form", class: "pull-left", role: "form" do |f|
      .col-xs-12.title-container
        h1 > Confirm your offer.
      .col-xs-12.left-container-content
        .col-xs-12.select-payment-container
          .col-xs-6.no-pad
        .col-xs-12.select-payment-container
          h3 OPTIONAL INFORMATION
          .form-container
            label.marg-top-23
              | Include a message for your seller, &nbsp;
              = @listing.seller.first_name
              | !
            = text_area_tag "message"
      .col-xs-12.left-container-content.submit-container
        .form-group
          = hidden_field_tag :offer_price, @offer_price
          = hidden_field_tag :listing_id, @listing.id
          = submit_tag "FINISH AND MAKE OFFER", class: "btn btn-warning"


  .col-xs-4
    .row
      .col-xs-11.box-container.right-container.no-pad
        .right-container-label
          | You are about to make an offer for:
        .right-container-content
          h4= @listing.title
          .post-container
            | POSTED &nbsp;
            b= @listing.created_at.strftime("%^b. %e")
            | &nbsp; by &nbsp;
            b= @listing.seller.first_name.upcase
          .price-container
            = number_to_currency(@offer_price, :locale => 'en_us', :precision => 0)
          -if @listing.images.present?
            .product-image-container style="background-image: url('#{image_url(@listing.images[0].image.url)}')"
          -else
            .product-image-container style="background-image: url('#{image_url("no_pic.jpg")}')"
          .product-guarantee-container
            span.black-check-icon
            p.pull-left Tapsell Buyer Guarantee
          .list-container
            .list
            .list
          .location-container
            | Pick up location: 
            = "UC San Diego"

app/views/offers/_credit_card_form.html.slim
= content_for :javascript_contents do
  = javascript_include_tag "offers"

= content_for :stylesheet_contents do
  = stylesheet_link_tag "offers"

.col-md-12.select-payment-container
  .form-container
    .form-group
      .row
        .col-md-7
          label Cardholder Name
          = text_field_tag :cc_billing_name, "", class: "form-control", autocomplete: "off"
        .col-md-3
          label Card Type
          = select_tag :card_type, options_for_select(["Visa", "MasterCard", "American Express"]), class: "form-control", placeholder: "Card Type"
    .form-group
      .row
        .col-lg-7
          label Card Number
          = text_field_tag :number, "", class: "form-control card-number", maxlength: "20", autocomplete: "off"
        .col-lg-3
          label Security Number
          = text_field_tag :cvc, "", class: "form-control security-number", maxlength: "4", autocomplete: "off"
    .form-group.no-marg
      .row
        .col-md-7
          .row
            .col-md-12
              label.pull-left.wid-100p Expiration Date
            .col-md-6
              = select_tag :exp_month, options_for_select(1..12), class: "form-control", placeholder: "month"
            .col-md-6
              = select_tag :exp_year, options_for_select((Date.today.year).upto(10.years.from_now.year)), class: "form-control", required: "true"
        .col-lg-3
           .row
            .col-md-12
              label Zipcode
              = text_field_tag "zipcode","", class: "form-control billing-zipcode"
= content_for :javascript_contents do
  = javascript_include_tag "jquery.numeric.js", "https://js.braintreegateway.com/v1/braintree.js"

app/views/offers/_sign_in_to_offer.html.slim
= content_for :javascript_contents do
  = javascript_include_tag "offers"

= content_for :stylesheet_contents do
  = stylesheet_link_tag "offers"

.container.marg-top-125
  .col-md-8.box-container.left-container
    .col-md-12.title-container
      h1 > Sign up to make an offer.
    .col-md-12.content-section
      p.content-section-title Why do I need to create an account?
      p Our service is built on trust, and part of that is knowing who you're buying from and selling to. User accounts create a safer community for everyone. Plus, it's fast and easy!
    .col-md-12.left-container-content
      h3 CREATE AN ACCOUNT
      .row
        .col-sm-12.no-pad
          .col-md-12.select-payment-container.purchase-signup-container
            = render "signup_form"
          .col-md-12.select-payment-container.purchase-signin-container
            = render "signin_form"
    .col-md-12.text-center.footer-container.sign-up-footer
      h4
        | Already on Tapsell? &nbsp;
        = link_to "Log in", "javascript:void(0);", class: "purchase-signin"
      p
        | By signing up you agree to our &nbsp;
        = link_to "Terms of Service", terms_path
    .col-md-12.text-center.footer-container.sign-in-footer
      h4
        | No account? &nbsp;
        = link_to "Join Tapsell", "javascript:void(0);", class: "purchase-signup"
  .col-md-4
    .row
      .col-md-11.box-container.right-container.no-pad
        .right-container-label
          | You are about to reserve the item:
        .right-container-content
          h4= @listing.title
          .post-container
            | POSTED &nbsp;
            b= @listing.created_at.strftime("%^b. %e")
            | &nbsp; by &nbsp;
            b= @listing.seller.first_name.upcase
          .price-container
            | $
            = @listing.price.to_i
          .product-guarantee-container
            span.black-check-icon
            p.pull-left Buyer guarantee
          .list-container
            .list
            .list
          .location-container
            | Pick up location: &nbsp;
            b= @listing.address

app/views/offers/_signin_form.html.slim
= content_for :javascript_contents do
  = javascript_include_tag "offers"

= content_for :stylesheet_contents do
  = stylesheet_link_tag "offers"

.col-md-5.no-pad.facebook-container
  = link_to "javascript:void(0);", class: "facebook-button" do
    span.fb-circle-icon
    p SIGN IN WITH FACEBOOK
.vertical-list.col-md-2.text-center
  .image-container.text-center
    = image_tag "/assets/vertical_list.png"
  p or
  .image-container.text-center
    = image_tag "/assets/vertical_list.png"
.col-md-5.no-pad.form-authentication
  = form_for(:session, :url => sessions_path, html: {class: "signin-form", role: "form"}) do |f|
    .row
      .form-title
        span.email-icon
        h3
          | SIGN IN WITH EMAIL
      .form-body
        .error-container
        .row
          .col-md-12.form-group
            = f.email_field :email, :required => false, class: "form-control signup-email", placeholder: "Your Email", :required => true, autocomplete: "false"
            p.registration-email.hide
          .col-md-12.form-group
            = f.password_field :password, :required => false, class: "form-control signup-password", placeholder: "Password", :required => true
          .col-md-12.form-group.text-center
            = f.submit "SIGN IN", class: "btn button-signup"

app/views/offers/_signup_form.html.slim
= content_for :javascript_contents do
  = javascript_include_tag "offers"

= content_for :stylesheet_contents do
  = stylesheet_link_tag "offers"

.col-md-5.no-pad.facebook-container
  = link_to "javascript:void(0);", class: "facebook-button" do
    span.fb-circle-icon
    p SIGN UP WITH FACEBOOK
.vertical-list.col-md-2.text-center
  .image-container.text-center
    = image_tag "/assets/vertical_list.png"
  p or
  .image-container.text-center
    = image_tag "/assets/vertical_list.png"
.col-md-5.no-pad.form-authentication
  = form_for(@user, url: users_path(@user), html: { :method => :post, class: "signup-form", role: "form", id: "registration-form"}) do |f|
    .row
      .form-title
        span.email-icon
        h3
          | SIGN UP WITH EMAIL
      .form-body
        .error-container
        .row
          .col-md-12.form-group
            = f.text_field :first_name, placeholder:"First Name", class: "form-control input", :required => true
          .col-md-12.form-group
            = f.text_field :last_name, placeholder:"Last Name", class: "form-control", :required => true
          .col-md-12.form-group
            = f.email_field :email, class: "form-control signup-email", placeholder: "Your Email", :required => true, autocomplete: "false"
            p.registration-email.hide
          .col-md-12.form-group
            = f.password_field :password, class: "form-control signup-password", placeholder: "Password", :required => true
          .col-md-12.form-group.text-center
            = f.submit "SIGN UP", class: "btn button-signup"

app/views/offers/offer_confirmation.html.slim
= content_for :stylesheet_contents do
  = stylesheet_link_tag "offers"
.container.marg-top-125
  .col-md-8.box-container.left-container
    .col-md-12.title-container
      span.green-check-icon
      h1.order-title
        | Congratulations,
        = current_user.first_name
        | .  Your offer has been placed.
    .col-md-12.left-container-content.pull-left
      .offer-confirmation
        span.black-check-icon
        p We've sent you an email confirmation of this offer.
        .list
    .col-md-12.text-center.order-footer
          .col-sm-2.text-center.no-pad
          = link_to "Browse more listings", listings_path, class: "link-to-account"
          .col-sm-2.text-center.no-pad
          = link_to "Go to my account", dashboard_path(current_user.id), class: "link-to-account"
  .col-md-4
    .row
      .col-md-11.box-container.right-container.no-pad
        .right-container-label
          | You made an offer for:
        .right-container-content
          h4= link_to @listing.title, listing_path(@listing)
          .post-container
            | POSTED &nbsp;
            b= @listing.created_at.strftime("%^b. %e")
            | &nbsp; by &nbsp;
            b= @listing.seller.first_name.upcase
          .price-container
            | $
            = @offer.price.to_i
          -if @listing.images.present?
            .product-image-container style="background-image: url('#{image_url(@listing.images[0].image.url)}')"
          -else
            .product-image-container style="background-image: url('#{image_url("no_pic.jpg")}')"
          .product-guarantee-container
          - #  span.black-check-icon
          - #  p.pull-left Tapsell Buyer Guarantee
          .list-container
            .list
            .list
          .location-container
            | Pick up location: 
            = "UC San Diego"